version: '3.3'

services:
  nginx:
    image: nginx:1.17-alpine
    depends_on:
      - wordpress
    ports:
      - 8080:80
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ./wordpress:/var/www/html
  mariadb:
    image: mariadb:10.4.6-bionic
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
    depends_on:
      - mariadb
    image: wordpress:5.2.2-php7.3-fpm-alpine
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
volumes:
  db_data: {}
